blueprint:
  name: Automate Ally
  description: Manage an Ally TRV
  domain: automation
  input:
    trv:
      name: Smart TRV
      description: The TRV to force
      selector:
        entity:
          domain: climate
    temperature_sensor:
      name: Temperature Sensor
      description: Sensor used to measure temperature changes
      selector:
        entity:
          domain: sensor
          device_class: temperature
    window_sensor:
      name: Window Sensor
      description: Sensor used to detect window opening
      default: "binary_sensor.sensor_bidon"
      selector:
        entity:
          domain: binary_sensor
          device_class: door

variables:
  trv: !input trv
  temperature_sensor: !input temperature_sensor
  window_sensor: !input window_sensor

triggers:
  - trigger: state
    entity_id:
      - !input window_sensor
    to: "on"
    for:
      hours: 0
      minutes: 0
      seconds: 0
    id: opened
  - trigger: state
    entity_id:
      - !input window_sensor
    to: "off"
    for:
      hours: 0
      minutes: 0
      seconds: 0
    id: closed
  - trigger: time_pattern
    minutes: /30
    id: time_triggered
  - trigger: state
    entity_id:
      - !input temperature_sensor
    id: set_temperature
conditions: []
actions:
  - if:
      - condition: trigger
        id:
              - opened
              - closed
              - time_triggered
    then:
          - action: "{{ 'switch.turn_' + states((device_entities(device_id(trv))  | select ('search', 'window_open_external$')) | list | last)}}"
            metadata: {}
            data: {}
            target:
              entity_id: "{{ (device_entities(device_id(trv))  | select ('search', 'window_open_external$')) | list | last }}"
  - if:
      - condition: trigger
        id:
              - set_temperature
              - time_triggered
    then:
          - action: number.set_value
            metadata: {}
            data:
              value: >-
                {{ ((states(temperature_sensor) |
                float ) * 100 )| int }}
            target:
              entity_id: "{{ (device_entities(device_id(trv))  | select ('search', 'external_measured_room_sensor$')) | list | last }}"
mode: queued
max: 10
trace:
  stored_traces: 20

