blueprint:
  name: TRV-Windows Sync
  description: Turn off TRV(s) on window(s) open
  domain: automation
  input:
    window_entity:
      selector:
        entity:
          domain:
            - binary_sensor
    trv_entities:
      selector:
        entity:
          domain:
            - climate
          multiple: true
    reaction_time_open:
      selector: 
        duration:
      default:
        hours: 0
        minutes: 2
        seconds: 0
    reaction_time_close:
      selector: 
        duration:
      default:
        hours: 0
        minutes: 10
        seconds: 0
mode: restart
alias: Synchronize TRV with its window(s)
description: ""
trigger:
  - platform: state
    entity_id: !input window_entity
    from: "off"
    to: "on"
    for: !input reaction_time_open
    id: window_open
  - platform: state
    entity_id: !input window_entity
    from: "on"
    to: "off"
    id: window_closed
    for: !input reaction_time_close
condition:
  - condition: state
    entity_id: input_boolean.chauffage_mode_ete
    state: "off"
action:
  - if:
      - condition: trigger
        id:
          - window_open
    then:
      - service: scene.create
        data:
          scene_id: "before_window_open_{{ trv_entities|join('-') }}"
          snapshot_entities: !input trv_entities
      - service: climate.set_temperature
        target:
          entity_id: !input trv_entities
        data:
          temperature: 5
    else:
      - service: scene.turn_on
        target:
          entity_id: "scene.{{ trigger_id }}_before_window_open"
