blueprint:
  name: TRV Booster
  description: Boost the TRV when temperature is below target (makes sure it is open)
  domain: automation

  input:
    trv:
      name: Smart TRV
      description: The TRV to force
      selector:
        entity:
          domain: climate
    temperature_sensor:
      name: Temperature Sensor
      description: Sensor used to measure temperature changes
      selector:
        entity:
          domain: sensor
          device_class: temperature
# We want the latest state to be the one that's going to be applied (we sleep 30s whatever happens, in case the trigger is human input)
mode: restart


variables:
  device_ieee: "{{ (device_attr(trv, 'identifiers')|list).0.1 }}"

trigger_variables:
  trv: !input trv
  temperature_sensor: !input temperature_sensor


trigger:
  - platform: template
    value_template: >-
      {{
      states(temperature_sensor)
      + 0.5 <
      state_attr(trv,'temperature') }}
    for:
      hours: 0
      minutes: 0
      seconds: 0

action:
  - delay: 30
  - service: zha.set_zigbee_cluster_attribute
    data:
      cluster_type: in
      ieee: "{{ device_ieee }}"
      endpoint_id: 1
      cluster_id: 61184
      attribute: 613
      value: "300"
